name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Log in to Container Registry
        run: echo "${{ secrets.OAUTH_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Check Docker image
        run:
          docker pull cr.yandex/${{ vars.CR_ID }}/app:${{ github.event.inputs.version }}_latest

      - name: Get current running container image
        id: current_image
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ vars.SERVER_IP }} "docker ps --filter 'name=app' --format '{{.Image}}'"

      - name: Deploy to production server
        run:
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ vars.SERVER_IP }} "
          sudo docker stop app &&
          sudo docker rm app &&
          sudo docker run -d --name app -p 3000:3000 cr.yandex/${{ vars.CR_ID }}/app:${{ github.event.inputs.version }}_latest"

      - name: Remove old Docker image
        if: steps.current_image.outputs.image != ''
        run: |
          OLD_IMAGE=${{ steps.current_image.outputs.image }}
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ vars.SERVER_IP }} "docker rmi $OLD_IMAGE -f"

      - name: Add comment to issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMITS: ${{ steps.get_commit_list.outputs.commits }}
        run: |
          ISSUE_NUMBER=$(gh issue list --search ${{ github.event.inputs.version }} --limit 1 --json number --jq ".[0].number")
          gh issue comment $ISSUE_NUMBER --body "Release v${{ github.event.inputs.version }} has been deployed to production.<br><br>**Date:** ${{ github.event.created_at }}<br>**Author:** ${{ github.actor }}"
