name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Log in to Container Registry
        run: echo "${{ secrets.OAUTH_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Check Docker image
        run:
          docker pull cr.yandex/$CR_ID/app:${{ github.event.inputs.version }}_latest

      - name: Deploy to production server
        run:
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USER }}@$SERVER_IP "docker run -d --name app -p 3000:3000 cr.yandex/$CR_ID/app:${{ github.event.inputs.version }}_latest"

      - name: Add comment to issue
        run: |
          ISSUE_NUMBER=$(gh issue list --label release --limit 1 --json number --jq ".[0].number")
          gh issue comment $ISSUE_NUMBER --body "Release ${{ github.event.inputs.version }} has been deployed to production.\n\nDate: ${{ github.event.created_at }}\nAuthor: ${{ github.actor }}"
